### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by artellblender** [sebastiandev/zipper#20]
Sorry if this is a really noobie question but i'm stuck at the compiling step on Windows.
"cmake ..\" gives the following error:

`CMake Error at CMakeLists.txt:167 (message):
  The include directory specified for zlib does not appear to be

  valid.  It should contain the file zlib.h, but it does not.  Please

  verify the LIBZ_INCLUDE_DIR variable.`

I tried to set a new environment variable ZLIBROOT = "c:\zlib"
Tried to add "c:\zlib\" to the Path variable too, no luck.

Any help very appreciated :-)

**Comment by sebastiandev** [comment]
Have you set LIBZ_INCLUDE_DIR to point to the path where zlib.h is located?

**Comment by artellblender** [comment]
Thanks for your reply Sebastian!
I've finally found a way by changing the paths to the zlib dir and dll in the "CMakeCache.txt" generated after the error... But I don't know if it's the good way.
The files are now generated without errors.
But the last step "make" does not work :-( It says there is not target/make file... Any advice?

**Comment by artellblender** [comment]
(it's make from cygwin64)

**Comment by artellblender** [comment]
After further investigations
:
-Using CMake GUI definitely helped solving the zlib path issues

-Compiling with MinGW leads to an error with <filesystem> in defs.h :
fatal error: filesystem: No such file or directory
#include <filesystem>

-Compiling with MVS 2017 leads unfortunately to other errors:
c:\zlib\zconf.h(477): fatal error C1083: cannot open include file : 'unistd.h' : No such file or directory

**Comment by 0ctothorp** [comment]
> -Compiling with MinGW leads to an error with<filesystem>in defs.h :
I have the same issue comiling on windows with MinGW32.

**Comment by sebastiandev** [comment]
I don't have a windows box so I cant really test it right now. @fbergmann any ideas here?

**Comment by fbergmann** [comment]
I have not tested with MingW32, which currently does not yet seem to support the filesystem api. Compilation will succeed with visual studio (which can be downloaded free of charge).

**Comment by 0ctothorp** [comment]
@fbergmann Yeah, I already figured that out. Compiling with Visual Studio works :) BTW is the <filesystem> a header for c++17 experimental filesystem api or is it something windows specific?

**Comment by fbergmann** [comment]
the filesystem api is not windows specific, but there is hardly any support in the std c++ libraries for it otherwise. That is why on other system i was using a class we wrote for out other project (COPASI). So all that will need to be done is to somehow detect mingw and then disable that include and default to the other one.

**Comment by Lecrapouille** [comment]
Hi, I'm also a noob with MinGW (I don't have Window) so I'm trying to compile zipper (in blind) with [appveyor](https://ci.appveyor.com), and I have the following error:
```
-- Looking for gzopen in LIBZ_LIBRARY-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBZ_LIBRARY
```
Note: I installed zlib and libzip with pacman but I do not know how to set ZLIBROOT as requested in the README:

> Note: For windows users, zlib is expected to be found at ZLIBROOT. 

Any help is welcomed :)

**Comment by fbergmann** [comment]
In this case you specifically pass along the -DLIBZ_LIBRARY= < path to libz library to link against > cheers frank

**Comment by Lecrapouille** [comment]
Hi @fbergmann ! Thx for your fast answer but I think it will be more difficult than just added -DLIBZ_LIBRARY.

In my case zlib.h seems to be located in `/mingw64/include/zlib.h` and `/mingw32/include/zlib.h` and therefore matching the CMakeLists.txt code line 124 `$ENV{ZLIBROOT}/include`. 

So, at beginning, I tried to do that:
```
cd zipper
mkdir build
cd build
export ZLIBROOT="/mingw64"
cmake ..
```

Unfortunately failed because I do not have zdll.lib or zlib.lib files like expected by CMakeLists.txt line 113 `$ENV{ZLIBROOT}/lib` In fact I have files libz.a and libz.dll.a located in /mingw64/lib

So I followed your answer:
```
cd zipper
mkdir build
cd build
export ZLIBROOT="/mingw64"
cmake -DLIBZ_LIBRARY="/mingw64/lib" ..
```

But failed:

> -- Looking for gzopen in C:/msys64/mingw64/lib
WARNING: Target "cmTC_80ddf" requests linking to directory "C:/msys64/mingw64/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cmTC_80ddf" requests linking to directory "C:/msys64/mingw64/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cmTC_80ddf" requests linking to directory "C:/msys64/mingw64/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cmTC_80ddf" requests linking to directory "C:/msys64/mingw64/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Looking for gzopen in C:/msys64/mingw64/lib - not found

Note: I do not have Window computer with MinGW so I have to work blindly with an appveyor script: edit it, git push it, and see results in appveyor logs. Feel free to use and adapt my [appveyor.yml script](https://github.com/Lecrapouille/SimTaDyn/blob/master/appveyor.yml) calling [the pacman install script](https://github.com/Lecrapouille/SimTaDyn/blob/master/.integration/appveyor-install-window.sh) for your own tests.

**Comment by oranja** [comment]
Seems like you would need to edit the **CMakeLists.txt** file, such that it either:
* takes a user-defined value for `LIBZ_LIBRARY`, in your case pointing straight to `/mingw64/lib/libz.a` (`if (NOT LIBZ_LIBRARY)`, followed by another `endif()` after the current one in @L128)
* or also accepts `zlib.a` in `NAMES` for LIBZ_LIBRARY (@L108)

Disclaimer: I did not test this solution. It's an educated guess.

**Comment by Lecrapouille** [comment]
@oranja, thanks you ! I had not time checking your suggestion yet. I postponed window CI for the moment.

**Comment by Lecrapouille** [comment]
Closed by https://github.com/sebastiandev/zipper/pull/76
