### ISSUE TITLE
Zip created by zipper can not be extracted using Windows or Win zip

### ISSUE THREAD

**Issue by AlexSolaris** [sebastiandev/zipper#27]
Hi i used code from tutorial like:
Zipper zipper("ziptest.zip");

	std::stringstream mSt;
	mSt << "TEST";
	zipper.add(mSt,"stuff.txt");
	zipper.close();

and the zip file is created on hdd.
Step 2: i try to extract file from zip just created using Winzip or Windows and it fails.. i mean you can see 
the content of the zip but when try to extract it fails.
The only one which can extract the file from archive with success is 7zip.
Is anyone aware of this issue ? Or maybe i am doing something wrong in the above code?!!!

Cheers,
Alex.

**Comment by Lecrapouille** [comment]
I'm probably wrong but the add() method takes an ifstream not a stringstream (see unit tests as example)

**Comment by oranja** [comment]
@Lecrapouille: It takes any `istream`.

@AlexSolaris:
I was already working on my Win10 VM, so I gave it a shot.
I had the following code (in `main.cpp`):
```c++
#include <zipper/zipper.h>
#include <sstream>

int main()
{
	zipper::Zipper zipper("ziptest.zip");
	
	std::stringstream ss;
	ss << "TEST";
	zipper.add(ss, "stuff.txt");
	
	zipper.close();
	
	return 0;
}
```
Compiled with:
```cmd
cl /MD /EHsc /IC:\Projects\lib\zipper main.cpp C:\Projects\lib\zipper\release\libzipper-static.lib "C:/Program Files/zlib/lib/zlibstatic.lib"
```
Then running `main.exe` creates a `ziptest.zip` file, which opened fine both with 7Zip and Windows 10's Explorer.

** Disclaimer: This test might be worthless because in my copy of Zipper the code is a little outdated and modified a little bit, but not in any way that I suspect could make much difference.

**Comment by Lecrapouille** [comment]
Closing this ticket is working (at least on Linux on my side, I cannot test on window). Feel free to reopen this ticket if needed
