### ISSUE TITLE
Build Instructions (Windows)

### ISSUE THREAD

**Issue by laxeot** [sebastiandev/zipper#3]
Hi there,
I'm not entirely sure how to build this, especially without taking advantage of CMake. Every time I attempt to use Visual Studio to build it, I keep running into countless linker errors and don't know where to start. Is there any way you can improve upon the build instructions? Thank you!

**Comment by sebastiandev** [comment]
Hey,
The project should build out of the box as is. First of all, remember its only C++11, an older version wont work because im making use of lambdas,  generators and all those fancy new things.
If you have c++11 then also have in mind that it was only tested on VS2013 and remember that it depends on zlib as it is explained on the configuration. 

If you are stil having problems, then paste the compilation output so I can take a look at the errors.
