### ISSUE TITLE
is zipper always actively developped ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [sebastiandev/zipper#44]
minizip seems not to be up to date and unicode encoding seems not to be managed on windows (path + password)

Are you planning to fix these issues soon?

**Comment by sebastiandev** [comment]
@Nelson-numerical-software there was a prolonged hiatus, but some of the guys that were using it on a daily basis offered to keep working on it, so right now it's been actively maintained.
we'll see if we can update, its probably just a matter of updating the references.

@Lecrapouille do you think is worth doing that, or maybe just remove the minizip submodule and let the users just use whatever minizip version they have installed?

**Comment by Lecrapouille** [comment]
I quickly look at last minizip repo, their files totally changed. For example, zip.h is now mz_zip.h, unzip.h does not exist :(

**Comment by sebastiandev** [comment]
hmm I guess it will have to be updated, but that would break older clients forcing them to update minizip, since they removed/renamed their header files...

Not sure what's the best approach here, dynamic linking would solve it and prevent future issues like this one, but still break older users too.
